### ISSUE TITLE
list-buffers not working

### ISSUE THREAD

**Issue by jgmtzmd** [Delapouite/kakoune-buffers#10]
hi.
i copied buffers.kak from (https://github.com/Delapouite/kakoune-buffers) and placed it in /usr/share/kak/rc/extra/

the command appears in the bar but when i select it. it reports an error:

> 1:1: 'list-buffers' 2:3: 'refresh-buffers-info' 4:3: 'eval' no such env var: modified

Information for package kakoune:
--------------------------------
Repository     : openSUSE-Leap-42.3-Oss               
Name           : kakoune                              
Version        : 0.0+git.20170513-1.10                
Arch           : x86_64                               
Vendor         : openSUSE                             
Installed Size : 2.7 MiB                              
Installed      : Yes                                  
Status         : up-to-date                           
Source package : kakoune-0.0+git.20170513-1.10.src    

what should i do to get this to work?

**Comment by jgmtzmd** [comment]
this is my kakrc if that matters..


colorscheme default
hook global InsertBegin .* %{ colorscheme base16 }
hook global InsertEnd .* %{ colorscheme default }
hook global NormalBegin .* %{ colorscheme default }


set global indentwidth 4
map global insert <tab> '<space><space><space><space>'

hook global WinCreate .* %{ autowrap-enable }

map global user y "xy" -docstring "copia linea."
map global user d "xd" -docstring "borra linea."
map global user w "be" -docstring "selecciona palabra."
map global user Y "<a-|> xsel -ib <ret>" -docstring "copia seleccion a portapapeles."
map global user o "o <esc>" -docstring "inserta renglon abajo."
map global user O "O <esc>" -docstring "inserta renglon arriba."
map global user s "i<space><esc>" -docstring "inserta espacio."
map global user <'> "i'<esc>a'<esc>" -docstring "entrecomilla simple."
map global user <"> 'i"<esc>a"<esc>' -docstring "entrecomilla doble."
map global user 1 "gi" -docstring "ir a inicio de linea."
map global user 2 "gl" -docstring "ir a fin de linea."
map global user 3 ":comment-line<ret>" -docstring "comenta linea."
map global user 4 "<a-`>" -docstring "cambia mayusc/minusc."
map global user 5 ":comment-block<ret>" -docstring "comenta bloque."

alias global bd delete-buffer
alias global qq quit!

#to map wq -> esc
hook global InsertChar q %{
    try %{
        exec -draft hH <a-k>wq<ret> d
        exec <esc>
    } }

hook global WinSetOption filetype=python %{
    jedi-enable-autocomplete
    #lint-enable
    #set-option global lintcmd 'flake8'
    }

**Comment by Delapouite** [comment]
Hello.

Your kakoune version seems quite outdated. `buffers.kak` should be compatible with https://github.com/mawww/kakoune/releases/tag/v2018.04.13 from last april.

Note that it has not been (yet) updated to work with the edge version.

**Comment by jgmtzmd** [comment]
i can confirm that it works well in newer kakoune version. thanks.

**Comment by vbauerster** [comment]
> Hello.
> 
> Your kakoune version seems quite outdated. `buffers.kak` should be compatible with https://github.com/mawww/kakoune/releases/tag/v2018.04.13 from last april.
> 
> Note that it has not been (yet) updated to work with the edge version.

Any plans to make it work with edge kakoune version?
