### ISSUE TITLE
buffer by index menu in buffer mode

### ISSUE THREAD

**Issue by koehlerson** [Delapouite/kakoune-buffers#25]
Hey, thanks for the nice plugin! It's probably a very novice question, but I'm wondering how I can get the buffer by index menu in buffer mode as depicted in the readme picture:
![image](https://user-images.githubusercontent.com/27497290/176433458-393a38f7-7547-4ab4-a48d-490d9e2b0d30.png)

**Comment by krobelus** [comment]
`git log -G': by index'` shows that the 1-9 bindings were changed in 8c2ab07 (feat: expose a dedicated 'buffers' user-mode, 2018-03-21). Now you can press `3b` etc. (if `b` is mapped to `enter-buffers-mode`)

**Comment by koehlerson** [comment]
@krobelus backbone of the kakoune community - at least everytime I use a certain plugin :D. Thank you, I was searching for this and good to know the commit where it has been changed
